drive:
    ros__parameters:
        visualization: false
        model_path: "/lanefollowing/ros2_ws/src/lane_following/e2e/model/model.h5"
        camera_topic: "/simulator/sensor/camera/center/compressed"
        control_topic: "/lanefollowing/steering_cmd"